services:
  - type: static site
    name: agentic-ai-optimizer-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 